modLoader = "javafml"
loaderVersion = "[36,)"
license = "All Rights Reserved unless stated otherwise. Distribution permission is given to FeedTheBeast and CurseForge for use in modpacks"
[[mods]]
modId = "ibicf"
version= "${file.jarVersion}"
displayName = "I Believe I Can Fly"
description = "Change the cloud height"
[[dependencies.ibicf]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
[[dependencies.ibicf]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,1.18)"
ordering = "NONE"
side = "BOTH"
